### ISSUE TITLE
What are you doing bro?

### ISSUE THREAD

**Issue by diyorbekrustamjonov** [Blood2Code/news#1]
**Why are you storing the API key here?**

https://github.com/Blood2Code/news/blob/c95fd151fc3ce02c9626bc1e86d88ea04e7f7273/src/main/java/org/task/news/service/NewsService.java#L31

**Comment by Blood2Code** [comment]
Yes, i know that i should not write an api key in public, but as u can see the newsapi.org gave an open api key like me, it says that they use registering us and giving an api keys to assembly more subscribers :)

**Comment by diyorbekrustamjonov** [comment]
If you're not well-versed in using the API key in the code, why are you using it like this? Regardless, the integrator will mention that you can use it anywhere, but such data should still be stored securely elsewhere!
